apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-replica
spec:
  serviceName: mongo
  replicas: 3
  selector:
    matchLabels:
      app: mongo
      role: mongodb
      environment: test
  template:
    metadata:
      labels:
        app: mongo
        selector: mongo
        role: mongodb
        environment: test
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccount: mongo-account
      containers:
      - name: mongodb
        image: andreastanderen/mongo-sts-3
        command:
          - mongod
          - "--bind_ip_all"
          - "--replSet"
          - rs0
        ports:
        - name: mongo-port
          containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        volumeMounts:
        - name: mongo-data
          mountPath: /data/mongo
      - name: mongo-sidecar
        image: cvallance/mongo-k8s-sidecar
        env:
          - name: MONGO_SIDECAR_POD_LABELS
            value: "role=mongodb,environment=test"
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: manual
      resources:
        requests:
          storage: 1Gi
