kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-data-claim
  namespace: mongo-statefulset
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: manual
