apiVersion: v1
kind: Service
metadata:
  name: mongodb-0-svc
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-replica-0
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-1-svc
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-replica-1
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32001
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-2-svc
spec:
  type: NodePort
  externalTrafficPolicy: Local
  selector:
    statefulset.kubernetes.io/pod-name: mongodb-replica-2
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32002
